//
//  Constants.h
//  hacktaon
//
//  Created by Pavlo Nadolinskyi on 7/14/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#ifndef hacktaon_Constants_h
#define hacktaon_Constants_h

//keys
#define ALBUMS_KEY          @"ALBUMS_KEY"
#define ERROR_KEY           @"ERROR_KEY"
#define THUMBNAILS_KEY      @"THUMBNAILS_KEY"


#define NOTIFICATION_FETCH_ALBUM_LIST_SUCCESS @"NOTIFICATION_FETCH_ALBUM_LIST_SUCCESS"
#define NOTIFICATION_FETCH_PHOTO_LIST_SUCCESS @"NOTIFICATION_FETCH_PHOTO_LIST_SUCCESS"
#define NOTIFICATION_THUMBNAIL_UPDATE_SUCCESS @"NOTIFICATION_THUMBNAIL_UPDATE_SUCCESS"

#define NOTIFICATION_UPLOAD_COMMENTS_SUCCESS @"NOTIFICATION_UPLOAD_COMMENTS_SUCCESS"
#define NOTIFICATION_UPLOAD_COMMENTS_FAILURE @"NOTIFICATION_UPLOAD_COMMENTS_FAILURE"


#define NOTIFICATION_CONVERTION_ENDED @"NOTIFICATION_CONVERTION_ENDED"

#define NOTIFICATION_REQUEST_ERROR @"NOTIFICATION_REQUEST_ERROR"


#endif
